export {default as Home} from './Home/Home'
export {default as Auth} from './Auth/Auth'
export {default as Registerition} from './Auth/Registerition'
export {default as RestThePassword} from './Auth/RestPassword'
export {default as ADetailes} from './Publications/ArticlesDetailes'
export {default as NDetailes} from './Publications/NewsDetailes'
export {default as L_news} from './Lists/NewsList'