export {default as Navbar} from './navBar/NavBar';
export {default as Homecard} from './Cards/HomeCard'
export {default as Newscard} from './Cards/NewsCard'
export {default as Latest} from './News/latest'
export {default as Topnews} from './News/topnews'
export {default as Toparticle} from './Article/TopArticle'
export {default as Latestarticle} from './Article/LatestArticle'
export {default as Singin} from './auth/SingIn'
export {default as SingUp} from './auth/SingUp'
export {default as MailCheck} from './auth/MailConfirmation'
export {default as Restpassword} from './auth/RestPassword'
export {default as Articledetailes} from './Detailes/Detailes'
export {default as Tools} from './Tools/Tools'
export { default as NewsDetaile} from './Detailes/N_detaile'
